
INSERT INTO `currencies_db`.`roles`(`id`,`role_name`) VALUES (1, 'ADMIN');
INSERT INTO `currencies_db`.`roles`(`id`,`role_name`) VALUES (2, 'USER');

# password adminadmin
INSERT INTO `currencies_db`.`users`(`id`, `username`,`first_name`, `second_name`, `password`, `email`)
VALUES (1, 'adminadmin', 'admin', 'admin', '$2a$10$/2phZorRcBv.p7encTb49ONKyQRNgf/33/E30xD1h7egWcVqZ.gIy','admin@mail.com');

INSERT INTO `currencies_db`.`user_role` (`user_id`, `role_id`) VALUES (1, 1);

INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (1, 'AED', 'United Arab Emirates Dirham');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (2, 'AFN', 'Afghan Afghani');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (3, 'ALL', 'Armenian Dram');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (4, 'AMD', 'Armenian Dram');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (5, 'ANG', 'Netherlands Antillean Guilder');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (6, 'AOA', 'Angolan Kwanza');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (7, 'ARS', 'Argentine Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (8, 'AUD', 'Australian Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (9, 'AWG', 'Aruban Florin');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (10, 'AZN', 'Azerbaijani Manat');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (11, 'BAM', 'Bosnia-Herzegovina Convertible Mark');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (12, 'BBD', 'Barbadian Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (13, 'BDT', 'Bangladeshi Taka');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (14, 'BGN', 'Bulgarian Lev');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (15, 'BHD', 'Bahraini Dinar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (16, 'BIF', 'Burundian Franc');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (17, 'BMD', 'Bermudan Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (18, 'BND', 'Brunei Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (19, 'BOB', 'Bolivian Boliviano');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (20, 'BRL', 'Brazilian Real');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (21, 'BSD', 'Bahamian Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (22, 'BTC', 'Bitcoin');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (23, 'BTN', 'Bhutanese Ngultrum');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (24, 'BWP', 'Botswanan Pula');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (25, 'BYN', 'New Belarusian Ruble');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (26, 'BYR', 'Belarusian Ruble');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (27, 'BZD', 'Belize Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (28, 'CAD', 'Canadian Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (29, 'CDF', 'Congolese Franc');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (30, 'CHF', 'Swiss Franc');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (31, 'CLF', 'Chilean Unit of Account (UF)');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (32, 'CLP', 'Chilean Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (33, 'CNY', 'Chinese Yuan');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (34, 'COP', 'Colombian Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (35, 'CRC', 'Costa Rican Colón');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (36, 'CUC', 'Cuban Convertible Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (37, 'CUP', 'Cuban Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (38, 'CVE', 'Cape Verdean Escudo');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (39, 'CZK', 'Czech Republic Koruna');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (40, 'DJF', 'Djiboutian Franc');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (41, 'DKK', 'Danish Krone');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (42, 'DOP', 'Dominican Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (43, 'DZD', 'Algerian Dinar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (44, 'EGP', 'Egyptian Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (45, 'ERN', 'Eritrean Nakfa');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (46, 'ETB', 'Ethiopian Birr');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (47, 'EUR', 'Euro');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (48, 'FJD', 'Fijian Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (49, 'FKP', 'Falkland Islands Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (50, 'GBP', 'British Pound Sterling');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (51, 'GEL', 'Georgian Lari');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (52, 'GGP', 'Guernsey Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (53, 'GHS', 'Ghanaian Cedi');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (54, 'GIP', 'Gibraltar Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (55, 'GMD', 'Gambian Dalasi');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (56, 'GNF', 'Guinean Franc');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (57, 'GTQ', 'Guatemalan Quetzal');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (58, 'GYD', 'Guyanaese Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (59, 'HKD', 'Hong Kong Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (60, 'HNL', 'Honduran Lempira');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (61, 'HRK', 'Croatian Kuna');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (62, 'HTG', 'Haitian Gourde');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (63, 'HUF', 'Hungarian Forint');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (64, 'IDR', 'Indonesian Rupiah');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (65, 'ILS', 'Israeli New Sheqel');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (66, 'IMP', 'Manx pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (67, 'INR', 'Indian Rupee');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (68, 'IQD', 'Iraqi Dinar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (69, 'IRR', 'Iranian Rial');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (70, 'ISK', 'Icelandic Króna');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (71, 'JEP', 'Jersey Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (72, 'JMD', 'Jamaican Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (73, 'JOD', 'Jordanian Dinar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (74, 'JPY', 'Japanese Yen');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (75, 'KES', 'Kenyan Shilling');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (76, 'KGS', 'Kyrgystani Som');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (77, 'KHR', 'Cambodian Riel');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (78, 'KMF', 'Comorian Franc');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (79, 'KPW', 'North Korean Won');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (80, 'KRW', 'South Korean Won');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (81, 'KWD', 'Kuwaiti Dinar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (82, 'KYD', 'Cayman Islands Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (83, 'KZT', 'Kazakhstani Tenge');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (84, 'LAK', 'Laotian Kip');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (85, 'LBP', 'Lebanese Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (86, 'LKR', 'Sri Lankan Rupee');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (87, 'LRD', 'Liberian Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (88, 'LSL', 'Lesotho Loti');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (89, 'LTL', 'Lithuanian Litas');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (90, 'LVL', 'Latvian Lats');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (91, 'LYD', 'Libyan Dinar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (92, 'MAD', 'Moroccan Dirham');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (93, 'MDL', 'Moldovan Leu');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (94, 'MGA', 'Malagasy Ariary');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (95, 'MKD', 'Macedonian Denar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (96, 'MMK', 'Myanma Kyat');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (97, 'MNT', 'Mongolian Tugrik');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (98, 'MOP', 'Macanese Pataca');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (99, 'MRO', 'Mauritanian Ouguiya');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (100, 'MUR', 'Mauritian Rupee');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (101, 'MVR', 'Maldivian Rufiyaa');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (102, 'MWK', 'Malawian Kwacha');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (103, 'MXN', 'Mexican Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (104, 'MYR', 'Malaysian Ringgit');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (105, 'MZN', 'Mozambican Metical');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (106, 'NAD', 'Namibian Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (107, 'NGN', 'Nigerian Naira');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (108, 'NIO', 'Nicaraguan Córdoba');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (109, 'NOK', 'Norwegian Krone');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (110, 'NPR', 'Nepalese Rupee');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (111, 'NZD', 'New Zealand Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (112, 'OMR', 'Omani Rial');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (113, 'PAB', 'Panamanian Balboa');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (114, 'PEN', 'Peruvian Nuevo Sol');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (115, 'PGK', 'Papua New Guinean Kina');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (116, 'PHP', 'Philippine Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (117, 'PKR', 'Pakistani Rupee');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (118, 'PLN', 'Polish Zloty');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (119, 'PYG', 'Paraguayan Guarani');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (120, 'QAR', 'Qatari Rial');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (121, 'RON', 'Romanian Leu');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (122, 'RSD', 'Serbian Dinar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (123, 'RUB', 'Russian Ruble');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (124, 'RWF', 'Rwandan Franc');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (125, 'SAR', 'Saudi Riyal');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (126, 'SBD', 'Solomon Islands Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (127, 'SCR', 'Seychellois Rupee');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (128, 'SDG', 'Sudanese Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (129, 'SEK', 'Swedish Krona');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (130, 'SGD', 'Singapore Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (131, 'SHP', 'Saint Helena Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (132, 'SLL', 'Sierra Leonean Leone');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (133, 'SOS', 'Somali Shilling');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (134, 'SRD', 'Surinamese Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (135, 'STD', 'São Tomé and Príncipe Dobra');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (136, 'SVC', 'Salvadoran Colón');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (137, 'SYP', 'Syrian Pound');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (138, 'SZL', 'Swazi Lilangeni');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (139, 'THB', 'Thai Baht');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (140, 'TJS', 'Tajikistani Somoni');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (141, 'TMT', 'Turkmenistani Manat');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (142, 'TND', 'Tunisian Dinar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (143, 'TOP', 'Tongan Paʻanga');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (144, 'TRY', 'Turkish Lira');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (145, 'TTD', 'Trinidad and Tobago Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (146, 'TWD', 'New Taiwan Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (147, 'TZS', 'Tanzanian Shilling');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (148, 'UAH', 'Ukrainian Hryvnia');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (149, 'UGX', 'Ugandan Shilling');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (150, 'USD', 'United States Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (151, 'UYU', 'Uruguayan Peso');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (152, 'UZS', 'Uzbekistan Som');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (153, 'VEF', 'Venezuelan Bolívar Fuerte');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (154, 'VND', 'Vietnamese Dong');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (155, 'VUV', 'Vanuatu Vatu');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (156, 'WST', 'Samoan Tala');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (157, 'XAF', 'CFA Franc BEAC');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (158, 'XAG', 'Silver (troy ounce)');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (159, 'XAU', 'Gold (troy ounce)');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (160, 'XCD', 'East Caribbean Dollar');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (161, 'XDR', 'Special Drawing Rights');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (162, 'XOF', 'CFA Franc BCEAO');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (163, 'XPF', 'CFP Franc');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (164, 'YER', 'Yemeni Rial');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (165, 'ZAR', 'South African Rand');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (166, 'ZMK', 'Zambian Kwacha (pre-2013)');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (167, 'ZMW', 'Zambian Kwacha');
INSERT INTO `currencies_db`.`currencies` (`id`, `name`, `description`) VALUES (168, 'ZWL', 'Zimbabwean Dollar');